"""Preset values for the pipeline."""

from __future__ import annotations

PRESETS: dict[str, dict[str, object]] = {
    "portrait": {
        "pattern_set": "soft_4x4",
        "contrast": 1.1,
        "gamma": 0.95,
        "thresholds": [51, 102, 153, 204],
        "subject_aware": True,
        "subject_background_threshold": 248,
        "subject_margin": 6,
        "subject_percentiles": [32, 52, 72, 88],
        "subject_blend": 0.75,
        "highlight_rolloff_start": 208,
        "highlight_rolloff_strength": 0.3,
        "edge_boost": 1,
        "edge_threshold": 12,
        "remove_isolated_black": False,
        "fill_white_holes": False,
    },
    "anime": {
        "pattern_set": "soft_4x4",
        "contrast": 1.15,
        "gamma": 0.92,
        "thresholds": [42, 96, 150, 208],
        "subject_aware": True,
        "subject_background_threshold": 248,
        "subject_margin": 8,
        "subject_percentiles": [35, 55, 74, 90],
        "subject_blend": 0.58,
        "highlight_rolloff_start": 205,
        "highlight_rolloff_strength": 0.26,
        "edge_boost": 0,
        "edge_threshold": 10,
        "remove_isolated_black": False,
        "fill_white_holes": False,
    },
    "icon": {
        "pattern_set": "default_2x2",
        "contrast": 1.2,
        "gamma": 1.0,
        "thresholds": [64, 112, 160, 224],
        "subject_aware": True,
        "subject_background_threshold": 250,
        "subject_margin": 4,
        "subject_percentiles": [28, 48, 68, 86],
        "subject_blend": 0.55,
        "highlight_rolloff_start": 224,
        "highlight_rolloff_strength": 0.7,
        "edge_boost": 0,
        "edge_threshold": 18,
        "remove_isolated_black": False,
        "fill_white_holes": False,
    },
    "photo": {
        "pattern_set": "soft_4x4",
        "contrast": 1.05,
        "gamma": 0.98,
        "thresholds": [48, 96, 144, 200],
        "subject_aware": True,
        "subject_background_threshold": 246,
        "subject_margin": 6,
        "subject_percentiles": [30, 50, 70, 88],
        "subject_blend": 0.75,
        "highlight_rolloff_start": 216,
        "highlight_rolloff_strength": 0.5,
        "edge_boost": 1,
        "edge_threshold": 14,
        "remove_isolated_black": False,
        "fill_white_holes": False,
    },
}


def get_preset(name: str) -> dict[str, object]:
    return dict(PRESETS.get(name, PRESETS["anime"]))
